# baseURL = "https://www.fantasymaps.org/"
languageCode = "en-us"
title = "FantasyMaps"
theme = "ananke"
sectionPagesMenu = "main"

[menu]
    [[menu.main]]
        identifier = "maps"
        name = "The Maps"
        title = "The Maps"
        url = "https://map.fantasymaps.org"
        weight = 110
    [[menu.main]]
        identifier = "patreon"
        name = "Patreon"
        title = "Patreon"
        url = "https://www.patreon.com/openfantasymap"
        weight = 120

[params]
  background_color_class = "bg-black"
  description = "Serious tech for non-serious worlds"
  facebook = ""
  twitter = "https://twitter.com/openfantasymap2"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCqtvFb_gqerBxvOUnJ-yETA"
  github = "https://www.github.com/openfantasymap"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  
  rss = ""

